### ISSUE TITLE
bug: Unexpected response error from the server.

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [logto-io/js#489]
### Describe the bug
Getting strange error setting up the client in deno.

Here is my current middleware implementation (a really quick version). I am getting an error from the `oidc-provider` package, which is called from the `handleSignInCallback`. The validation of the code and state goes through, no issues there.

my logto config:

```typescript
export const logtoConfig = {
  endpoint: "http://localhost:3001",
  appId: "zvu934dt2ptcvj71qccax",
  appSecret: "oj32y9yhq7tj4rxkh87o7",
  baseUrl: "http://localhost:8000",
};
```
Middleware:

```typescript
import { MiddlewareHandlerContext } from "$fresh/server.ts";
import {
  cookieSession,
  WithSession,
} from "https://deno.land/x/fresh_session@0.2.0/mod.ts";
import Client, { createRequester } from "https://esm.sh/@logto/client@2.0.0";
import {
  generateCodeChallenge,
  generateCodeVerifier,
  logtoConfig,
} from "../utils/logto.ts";
import process from "https://deno.land/std@0.177.0/node/process.ts";

process.env.APP_KEY = "w4q0ovkv8v6tk49j328vlz93zravr1p4";

export type State = {} & WithSession;

const session = cookieSession({ maxAge: 14 * 24 * 60 * 60 });

function sessionHandler(req: Request, ctx: MiddlewareHandlerContext<State>) {
  return session(req, ctx);
}

async function authHandler(req: Request, ctx: MiddlewareHandlerContext<State>) {
  const { session } = ctx.state;

  let signInUriResponse: Response | null = null;

  const client = new Client(logtoConfig, {
    requester: createRequester(fetch),
    storage: {
      getItem: (key: string) => session.get(key),
      // deno-lint-ignore require-await
      setItem: async (key: string, value: string) => {
        session.set(key, value);
      },
      // deno-lint-ignore require-await
      removeItem: async (key: string) => {
        session.set(key, undefined);
      },
    },
    navigate: (url: string) => {
      signInUriResponse = new Response(null, {
        status: 307,
        headers: { Location: url },
      });
    },
    generateState: generateCodeVerifier,
    generateCodeVerifier: generateCodeVerifier,
    generateCodeChallenge: generateCodeChallenge,
  });

  const user = await client.isAuthenticated();

  if (!user && req.url.includes("auth")) {
    await client.signIn(logtoConfig.baseUrl);
    return signInUriResponse;
  } else if (!user && req.url.includes("code=")) {
    await client.handleSignInCallback(req.url);
  }

  return ctx.next();
}

export const handler = [sessionHandler, authHandler];
```
Error read out from the logto admin panel:
```json
{
  "ip": "::ffff:10.89.1.11",
  "key": "ExchangeTokenBy.AuthorizationCode",
  "error": "{\"stack\":\"InvalidClientAuth: invalid_client\\n    at auth (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/token_auth.js:168:17)\\n    at dispatch (/etc/logto/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\\n    at loadClient (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/token_auth.js:152:15)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async setWWWAuthenticateHeader (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/token_auth.js:43:11)\\n    at async selectiveBody (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)\\n    at async noCache (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)\\n    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@4.0.0/node_modules/@koa/cors/index.js:105:16)\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async ensureSessionSave (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)\\n    at async contextEnsureOidc (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)\\n    at async file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/helpers/initialize_app.js:222:5\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.0.0/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async file:///etc/logto/packages/core/build/middleware/koa-body-etag.js:11:9\\n    at async file:///etc/logto/packages/core/build/middleware/koa-audit-log.js:98:13\\n    at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5\",\"message\":\"invalid_client\",\"allow_redirect\":true,\"name\":\"InvalidClientAuth\",\"error\":\"invalid_client\",\"status\":401,\"statusCode\":401,\"expose\":true,\"error_description\":\"client authentication failed\",\"error_detail\":\"the provided authentication mechanism does not match the registered client authentication method\"}",
  "params": {
    "code": "69loPMgaa35d-lXm4lz7fU8jVh3rid-s5ZrwvxMw_Qs",
    "client_id": "zvu934dt2ptcvj71qccax",
    "grant_type": "authorization_code",
    "redirect_uri": "http://localhost:8000",
    "code_verifier": "err3mTUYAhg_RgK-mo8FPV5E93CtG0neiAz0RUd3k3aLs9JWzt7CoHIzwkSOsTdh6QM5n3kHxaD8GQx00Doq6Q"
  },
  "result": "Error",
  "userAgent": "Deno/1.33.1",
  "tokenTypes": [],
  "applicationId": "zvu934dt2ptcvj71qccax"
}
```
Error throwed by the client: 

```
Unexpected response error from the server.
```

### Expected behavior
Should work as in node, if the issue is from the configuration a clearer message would be better.

### How to reproduce?
I posted al the code I have in the bug description.

### Context
This is currently a locally hosted logto instance running in docker, and I am trying to log in from a locally running deno [fresh](https://fresh.deno.dev/) app.

- [ ] Logto Cloud
- [ x] Self-hosted, Logto version = 
  - [ x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by wangsijie** [comment]
@charIeszhao @simeng-li anyone familar with Deno?

**Comment by charIeszhao** [comment]
Not 100 sure but can you show us the application type for ID: zvu934dt2ptcvj71qccax?
Is it traditional web?

**Comment by TheOnlyBeardedBeast** [comment]
@charIeszhao yes, I used traditional web app.

**Comment by charIeszhao** [comment]
I did some research and can confirm the error was thrown from our underlying library `node-oidc-provider`. It seems the client ID (appId) you provided couldn't be found. Please check the source code: https://github.com/panva/node-oidc-provider/blob/949e2e576af3433063f0db5f16cbcd4ef8ad474f/lib/actions/authorization/check_client.js#L83

So can you double check if the client ID (appId) you provided exists in the Logto instance you were testing against?

**Comment by TheOnlyBeardedBeast** [comment]
So my project was iced, so I had to recreat the whole container. But I am getting the same error, I will paste here as much info as I can.

My new configuration in code:
```
export const logtoConfig = {
  endpoint: "http://localhost:3001",
  appId: "24m2qrbzcelw959yw6vgj",
  appSecret: "7eylf0s98e2jhjhrjgamg",
  baseUrl: "http://localhost:8000",
};
```

Configuration screenshot from logto, 
<img width="1185" alt="Screenshot 2023-07-06 at 07 55 33" src="https://github.com/logto-io/js/assets/55414686/0e0e3c5e-e1d5-4c83-ad29-ceda767449b4">

error response comes back on the redirected url
`http://localhost:8000/?code=NrcaOclK0jHgjNxolONVqfl5hVPPVjWEug67MogyabF&state=4OFE_Uh3Wf1gw7wbUdxcsIpf141VwYN0hIGlL7oQ3WHhrPmS4zovCG09axlekbUh0OhEg853yczl-SNRnz9ocA&iss=http%3A%2F%2Flocalhost%3A3001%2Foidc`

<img width="501" alt="Screenshot 2023-07-06 at 07 59 50" src="https://github.com/logto-io/js/assets/55414686/dc3838cf-3626-46cb-a6f6-f43bc7c6294c">
<img width="1252" alt="Screenshot 2023-07-06 at 08 00 10" src="https://github.com/logto-io/js/assets/55414686/84f38408-84ae-488c-acd3-7de83e704da2">

Logto audit log shows this error:
<img width="1170" alt="Screenshot 2023-07-06 at 07 56 49" src="https://github.com/logto-io/js/assets/55414686/555aaa89-04d7-4b1c-8b7e-b78ab22fb833">
<img width="1187" alt="Screenshot 2023-07-06 at 07 57 11" src="https://github.com/logto-io/js/assets/55414686/39033b76-6bb8-44e9-a9d5-79c5f0c2cb7a">


raw message from the audit log
```
{
  "ip": "::ffff:10.89.1.3",
  "key": "ExchangeTokenBy.AuthorizationCode",
  "error": "{\"stack\":\"InvalidClientAuth: invalid_client\\n    at auth (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:168:17)\\n    at dispatch (/etc/logto/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)\\n    at loadClient (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:152:15)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async setWWWAuthenticateHeader (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:43:11)\\n    at async selectiveBody (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)\\n    at async noCache (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)\\n    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@4.0.0/node_modules/@koa/cors/index.js:105:16)\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async ensureSessionSave (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)\\n    at async contextEnsureOidc (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)\\n    at async file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:222:5\\n    at async errorHandler (file:///etc/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async file:///etc/logto/packages/core/build/middleware/koa-body-etag.js:11:9\\n    at async file:///etc/logto/packages/core/build/middleware/koa-audit-log.js:98:13\\n    at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5\",\"message\":\"invalid_client\",\"allow_redirect\":true,\"name\":\"InvalidClientAuth\",\"error\":\"invalid_client\",\"status\":401,\"statusCode\":401,\"expose\":true,\"error_description\":\"client authentication failed\",\"error_detail\":\"the provided authentication mechanism does not match the registered client authentication method\"}",
  "params": {
    "code": "NrcaOclK0jHgjNxolONVqfl5hVPPVjWEug67MogyabF",
    "client_id": "24m2qrbzcelw959yw6vgj",
    "grant_type": "authorization_code",
    "redirect_uri": "http://localhost:8000",
    "code_verifier": "1iln87lVHRAX0stzU5j2ddfjnIsX7P9MBrMitgf49LvbZ0mO6HUqCeorbs14he_HN7P6bVXUo3ud5R-zSorNHw"
  },
  "result": "Error",
  "userAgent": "Deno/1.33.1",
  "tokenTypes": [],
  "applicationId": "24m2qrbzcelw959yw6vgj"
}
```

**Comment by charIeszhao** [comment]
Interesting... This time it returns `\"error_detail\":\"the provided authentication mechanism does not match the registered client authentication method\"`

Can you please create a minimal reproducible project, so that we can dive in and help investigate the root cause? Thanks

**Comment by TheOnlyBeardedBeast** [comment]
@charIeszhao couldnt the error detail change because I initialized the latest logto image for recreating my logto container? Also, I will create a small project later for debugging testing...

**Comment by wangsijie** [comment]
@TheOnlyBeardedBeast What type of SDK did you use? The token-related requests for traditional web app are required to have `Authorization` header, you can check our Node.js SDK code: https://github.com/logto-io/js/blob/0a533f616bf3100e57633ec62d8bd64ef30f7135/packages/node/src/index.ts#L42

**Comment by charIeszhao** [comment]
I think he's using `client` sdk

**Comment by TheOnlyBeardedBeast** [comment]
@wangsijie I am using the official @logto/client from npm provided by esm.sh so I can use it with deno

**Comment by wangsijie** [comment]
Then you'll need to add the Authorization header

**Comment by polakmark** [comment]
@wangsijie so in the createRequester like here? https://github.com/logto-io/js/blob/master/packages/node/src/index.ts

**Comment by TheOnlyBeardedBeast** [comment]
@wangsijie So in the createRequester like in this file @wangsijie so in the createRequester like here? https://github.com/logto-io/js/blob/master/packages/node/src/index.ts

**Comment by TheOnlyBeardedBeast** [comment]
@wangsijie @charIeszhao  thnaks for all the help the missing header was the issue, by adding the header it works without issues, I am able to signup and signin without any error message!
