### ISSUE TITLE
bug: When a page user logs in, an error will occur on the callview page, an infinite loop of printing error messages.

### ISSUE THREAD

**Issue by Mran** [logto-io/js#516]
Using logo1.5 and @ logo/vue 2.0.1 versions,
When a user logs in, there is a small probability that an error will occur on the callview page. When checking the control, it is found that there is an infinite loop of printing error messages.
The callback page uses the official recommended writing method

使用logto1.5版本和@logto/vue 2.0.1版本,
用户登录时，小概率会出现在callview页面出错的情况，查看控制发现无限循环打印错误信息。也不给跳出的机会.
callbak page 使用的是官方推荐写法.

这个是引起错误的url
> http://127.0.0.1:5173/callback?error=invalid_target&error_description=resource%20indicator%20must%20be%20an%20absolute%20URI&state=RA8oJLat9V6-TO61udded36nYCOLu3Z0caYFYuok8yAZRKEtw-FL-q5MwvZRCDQxIbxuAm5zUjL_yLCvILeAxg&iss=https%3A%2F%2Faccount.kcpop.plus%2Foidc

![image](https://github.com/logto-io/js/assets/4069404/080ab2fd-c30c-4a40-9074-6f08a1cace4d)

**Comment by Mran** [comment]
怀疑是这里引起的
 https://github.com/logto-io/js/blob/3b0cd4ab522de4682d3de1fac39d9a870ad055db/packages/vue/src/index.ts#L127C13-L127C13

**Comment by charIeszhao** [comment]
I'll take a look. Thanks for reporting.
Would be great if you can also provide the code in your `CallbackView.vue`, thanks

**Comment by Mran** [comment]
> I'll take a look. Thanks for reporting. Would be great if you can also provide the code in your `CallbackView.vue`, thanks
```
<template>
  <!-- 当登录认证尚未完成时 -->
  <p v-if="isLoading">正在重定向...</p>
</template>
<script setup lang="ts">
import { useHandleSignInCallback } from "@logto/vue";
import { useRouter } from "vue-router";
import { onMounted, ref } from "vue";


const router = useRouter();

const { isLoading } = useHandleSignInCallback(() => {
  router.push({ path: "/" });
  // 完成时跳转至根路由

});
</script>
@charIeszhao 
```

**Comment by Mran** [comment]
I add  await to  Line 140 , https://github.com/logto-io/js/issues/516#issuecomment-1606745621 ,and  no infinite loop message again 
```
 if (!isAuthenticated.value  && await logtoClient.value?.isSignInRedirected(currentPageUrl)) {
     
            void handleSignInCallback(currentPageUrl, callback);
        }
```

**Comment by Mran** [comment]
some time with  infinite loop request 
i can see a lot of aduit logs like this
```
 {
  "ip": "36.44.103.36",
  "key": "ExchangeTokenBy.AuthorizationCode",
  "error": "{\"stack\":\"InvalidGrant: invalid_grant\\n    at authorizationCodeHandler (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/grants/authorization_code.js:50:11)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async callTokenHandler (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:70:7)\\n    at async allowedGrantTypeCheck (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:53:7)\\n    at async supportedGrantTypeCheck (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:45:7)\\n    at async stripGrantIrrelevantParams (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/actions/token.js:33:7)\\n    at async auth (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:257:9)\\n    at async loadClient (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:152:9)\\n    at async setWWWAuthenticateHeader (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/token_auth.js:43:11)\\n    at async selectiveBody (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)\\n    at async noCache (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/no_cache.js:3:3)\\n    at async errorHandler (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\\n    at async ensureSessionSave (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:52:7)\\n    at async contextEnsureOidc (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)\\n    at async file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/helpers/initialize_app.js:222:5\\n    at async errorHandler (file:///home/ubuntu/logto/node_modules/.pnpm/oidc-provider@8.2.2/node_modules/oidc-provider/lib/shared/error_handler.js:26:7)\",\"message\":\"invalid_grant\",\"allow_redirect\":true,\"name\":\"InvalidGrant\",\"error\":\"invalid_grant\",\"status\":400,\"statusCode\":400,\"expose\":true,\"error_description\":\"grant request is invalid\",\"error_detail\":\"authorization code is expired\"}",
  "params": {
    "code": "kFHUwZoGs5sl-mFeJVAInS3bFPNmgU4WXoDxUAv95oO",
    "client_id": "Kt9cFEpDfun4xfkGorjZa",
    "grant_type": "authorization_code",
    "redirect_uri": "https://www.kcp.plus/callback",
    "code_verifier": "VbrP8bJbpYG9JhYonHd7yRdV-rNJPqsoc8UHAjGH7Zq-tRIM_O2M820m5mtbTP0eE9gUT1h0XyfflglhJ0ozBQ"
  },
  "result": "Error",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58",
  "tokenTypes": [],
  "applicationId": "Kt9cFEpDfun4xfkGorjZa"
}
```
