### ISSUE TITLE
bug: useRuntimeConfig is not defined

### ISSUE THREAD

**Issue by KevinLeneschmidt** [logto-io/js#650]
After installing the new version "0.1.1", it shows the message "useRuntimeConfig is not defined".

Like this:

500
useRuntimeConfig is not defined

at Object.handler (./node_modules/@logto/nuxt/dist/runtime/server/event-handler.mjs:5:18)
at Object.handler (./node_modules/h3/dist/index.mjs:1962:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
at errorhandler (./node_modules/nuxt/dist/core/runtime/nitro/error.js:37:41)
at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2256:9)

![Bildschirmfoto 2024-03-06 um 10 29 17](https://github.com/logto-io/js/assets/138887260/92f51f0c-199f-4630-965b-0ac2454c8f96)

**Comment by gao-sun** [comment]
taking a look

**Comment by gao-sun** [comment]
I have auto import turned on on the nuxt SDK project, so some imports may missing - turning off to see if it helps
